name: Bump version
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: Bump version and push tag
      id: Bump
      uses: anothrNick/github-tag-action@1.36.0
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
        WITH_V: true
        DEFAULT_BUMP : patch

    - name: Set version number
      run: |
        echo github variable ${{steps.bump.outputs.new_tag}}
        echo github variable ${{steps.bump.outputs.tag}}    